### ISSUE TITLE
Question on code release

### ISSUE THREAD

**Issue by 22222bh** [zijinwuzijin/DoF-NeRF#1]
Hi teams, thank you for your brilliant work!

Would you like to let me know when you gonna release your code? I think code can help me catch some concepts better.

Thanks!

**Comment by zijinwuzijin** [comment]
I am rather sorry about the late release of our code. We had scheduled to release our code before 2023, but I am still recovering from the COVID-19 infection. We are currently collating our code and data. We will release our code in the next few weeks.
